# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCP3A5aLqE2ycn7b6JwcF6P7nunTez_1
"""

!pip install streamlit pyngrok numpy matplotlib plotly -q

import streamlit as st
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# ==========================================
# 1. PAGE CONFIGURATION & THEME SETUP
# ==========================================
st.set_page_config(
    page_title="Intelligent Mud & Cement Design Suite",
    page_icon="⚓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Industrial CSS Styling
st.markdown("""
    <style>
        .main { background-color: #0E1117; }
        .stMetric { background-color: #1E222A; padding: 15px; border-radius: 8px; border-left: 5px solid #00D4FF; }
        h1, h2, h3 { color: #F5F5F5; }
    </style>
""", unsafe_allow_html=True)

st.title("⚓ Intelligent Mud & Cement Design Suite (PyMudCement-Optima)")
st.caption("PENG 258 Drilling & Cementing Engineering Capstone Project")
st.markdown("---")

# ==========================================
# 2. USER AUTHENTICATION & AUDIT SYSTEM
# ==========================================
if "authenticated" not in st.session_state:
    st.session_state.authenticated = False
if "worker_id" not in st.session_state:
    st.session_state.worker_id = ""

if not st.session_state.authenticated:
    st.sidebar.subheader("🔒 Engineer Authentication")
    worker_input = st.sidebar.text_input("Engineer / Student ID")
    password_input = st.sidebar.text_input("Access Password", type="password")

    if st.sidebar.button("Log In"):
        if worker_input and password_input == "peng258":
            st.session_state.authenticated = True
            st.session_state.worker_id = worker_input
            st.sidebar.success(f"Welcome, {worker_input}")
            st.rerun()
        else:
            st.sidebar.error("Invalid Credentials. (Default Pass: peng258)")

    st.warning("⚠️ Access restricted. Please authenticate via the sidebar to access computational modules.")
    st.stop()

st.sidebar.success(f"Active Session: **{st.session_state.worker_id}**")
if st.sidebar.button("Logout"):
    st.session_state.authenticated = False
    st.rerun()

# ==========================================
# 3. NAVIGATION TABS
# ==========================================
tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "💧 Drilling Hydraulics",
    "🧱 Cementing Volumetrics",
    "🎯 3D Directional Telemetry",
    "🛠️ P&A / Sidetrack Planning",
    "📄 Audit & PDF Export"
])

# ==========================================
# TAB 1: DRILLING HYDRAULICS & RHEOLOGY
# ==========================================
with tab1:
    st.header("Drilling Fluid Hydraulics Engine")

    col1, col2 = st.columns(2)
    with col1:
        mud_weight = st.number_input("Mud Weight - MW (ppg)", value=10.0, step=0.1, min_value=7.0, max_value=20.0)
        tvd = st.number_input("True Vertical Depth - TVD (ft)", value=10000.0, step=100.0)
        flow_rate = st.number_input("Flow Rate - Q (gpm)", value=450.0, step=10.0)

    with col2:
        pv = st.number_input("Plastic Viscosity - PV (cP)", value=20.0, step=1.0)
        yp = st.number_input("Yield Point - YP (lb/100ft²)", value=15.0, step=1.0)
        hole_diam = st.number_input("Hole Diameter (in)", value=8.5, step=0.125)
        pipe_od = st.number_input("Drill Pipe Outer Diameter (in)", value=5.0, step=0.25)

    # Core Engineering Equations (Bingham Plastic & Annular Velocity)
    hydrostatic_p = 0.052 * mud_weight * tvd
    annular_area = (hole_diam**2 - pipe_od**2)
    annular_vel = (24.5 * flow_rate) / annular_area if annular_area > 0 else 0
    ecd = mud_weight + (yp / (11.7 * (hole_diam - pipe_od))) if (hole_diam - pipe_od) > 0 else mud_weight

    st.markdown("---")
    st.subheader("Calculated Hydraulics Output")

    m1, m2, m3 = st.columns(3)
    m1.metric("Hydrostatic Pressure", f"{hydrostatic_p:,.2f} psi")
    m2.metric("Annular Velocity", f"{annular_vel:,.2f} ft/min")
    m3.metric("Equivalent Circulating Density (ECD)", f"{ecd:,.2f} ppg")

# ==========================================
# TAB 2: CEMENTING VOLUMETRICS
# ==========================================
with tab2:
    st.header("Cement Slurry & Primary Cementing Volumetrics")

    c1, c2 = st.columns(2)
    with c1:
        hole_size = st.number_input("Open Hole Outer Diameter (in)", value=8.5, key="c_hole")
        casing_od = st.number_input("Casing Outer Diameter (in)", value=7.0, key="c_od")
        casing_id = st.number_input("Casing Inner Diameter (in)", value=6.151, key="c_id")
        washout_factor = st.number_input("Excess / Washout Factor (%)", value=15.0, step=1.0)

    with c2:
        toc_depth = st.number_input("Top of Cement Depth - TOC (ft)", value=6000.0, step=100.0)
        shoe_depth = st.number_input("Casing Shoe Depth (ft)", value=10000.0, step=100.0)
        float_collar = st.number_input("Float Collar Depth (ft)", value=9920.0, step=50.0)
        slurry_yield = st.number_input("Slurry Yield (ft³/sack)", value=1.18, step=0.01)

    # Volumetric Computations
    annular_len = shoe_depth - toc_depth
    annular_cap = ((hole_size**2 - casing_od**2) / 1029.4) * (1 + (washout_factor / 100))  # bbl/ft with washout
    shoe_track_cap = ((casing_id**2) / 1029.4) * (shoe_depth - float_collar)  # bbl

    total_cement_bbl = (annular_cap * annular_len) + shoe_track_cap
    total_sacks = (total_cement_bbl * 5.6146) / slurry_yield if slurry_yield > 0 else 0

    st.markdown("---")
    st.subheader("Cement Job Requirements")

    cm1, cm2, cm3 = st.columns(3)
    cm1.metric("Annular Capacity (w/ Washout)", f"{annular_cap:.4f} bbl/ft")
    cm2.metric("Total Slurry Volume", f"{total_cement_bbl:,.2f} bbl")
    cm3.metric("Required Cement Bags", f"{total_sacks:,.0f} sacks")

# ==========================================
# TAB 3: 3D DIRECTIONAL TELEMETRY
# ==========================================
with tab3:
    st.header("3D Directional Wellbore Trajectory")

    # Synthetic Well Profile Data Generation
    md_points = np.linspace(0, tvd, 50)
    inc_angle = np.radians(np.linspace(0, 35, 50))
    azimuth_angle = np.radians(np.full(50, 45))

    z_depth = md_points * np.cos(inc_angle)
    x_east = md_points * np.sin(inc_angle) * np.sin(azimuth_angle)
    y_north = md_points * np.sin(inc_angle) * np.cos(azimuth_angle)

    fig_3d = go.Figure(data=[go.Scatter3d(
        x=x_east, y=y_north, z=z_depth,
        mode='lines+markers',
        line=dict(color='#00D4FF', width=6),
        marker=dict(size=3, color='#FF5B00'),
        name="Wellbore Profile"
    )])

    fig_3d.update_layout(
        scene=dict(
            xaxis_title="East / West Displacement (ft)",
            yaxis_title="North / South Displacement (ft)",
            zaxis_title="True Vertical Depth (ft)",
            zaxis=dict(autorange="reversed")
        ),
        height=550,
        margin=dict(l=0, r=0, b=0, t=20)
    )
    st.plotly_chart(fig_3d, use_container_width=True)

# ==========================================
# TAB 4: P&A / SIDETRACK PLANNING
# ==========================================
with tab4:
    st.header("Plug & Abandonment (P&A) / Whipstock Sidetrack Design")

    p1, p2 = st.columns(2)
    with p1:
        plug_top = st.number_input("Plug Top Depth (ft)", value=7000.0, step=50.0)
        plug_bottom = st.number_input("Plug Bottom Depth (ft)", value=7500.0, step=50.0)
    with p2:
        plug_hole_id = st.number_input("Plug Hole Diameter (in)", value=8.5)
        plug_slurry_yield = st.number_input("Plug Slurry Yield (ft³/sk)", value=1.15)

    plug_length = plug_bottom - plug_top
    plug_vol_bbl = ((plug_hole_id**2) / 1029.4) * plug_length
    plug_sacks = (plug_vol_bbl * 5.6146) / plug_slurry_yield if plug_slurry_yield > 0 else 0

    st.markdown("---")
    st.subheader("Plug Design Results")
    pa1, pa2, pa3 = st.columns(3)
    pa1.metric("Plug Length", f"{plug_length:,.2f} ft")
    pa2.metric("Plug Slurry Volume", f"{plug_vol_bbl:,.2f} bbl")
    pa3.metric("Cement Required", f"{plug_sacks:,.0f} sacks")

# ==========================================
# TAB 5: AUDIT LOG & PDF REPORT EXPORT
# ==========================================
with tab5:
    st.header("Audit Summary & Automated PDF Reporting")
    st.write("Generate a formal PDF engineering report based on active session parameter inputs.")

    def compile_pdf_report():
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=letter)

        # Header
        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(50, 750, "INTELLIGENT MUD & CEMENT DESIGN SUITE")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(50, 735, f"Engineer ID: {st.session_state.worker_id} | Course: PENG 258 Project")
        pdf.line(50, 725, 550, 725)

        # Hydraulics Section
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(50, 700, "1. Hydraulics & Rheology")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(70, 680, f"Mud Density: {mud_weight} ppg")
        pdf.drawString(70, 665, f"TVD Depth: {tvd:,.2f} ft")
        pdf.drawString(70, 650, f"Hydrostatic Pressure: {hydrostatic_p:,.2f} psi")
        pdf.drawString(70, 635, f"Equivalent Circulating Density (ECD): {ecd:,.2f} ppg")

        # Cementing Section
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(50, 605, "2. Cementing Volumetrics")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(70, 585, f"TOC Depth: {toc_depth:,.2f} ft | Shoe Depth: {shoe_depth:,.2f} ft")
        pdf.drawString(70, 570, f"Total Cement Volume Required: {total_cement_bbl:,.2f} bbl")
        pdf.drawString(70, 555, f"Total Cement Sacks Required: {total_sacks:,.0f} sacks")

        # P&A Section
        pdf.setFont("Helvetica-Bold", 12)
        pdf.drawString(50, 525, "3. P&A Cement Plug Summary")
        pdf.setFont("Helvetica", 10)
        pdf.drawString(70, 505, f"Plug Interval: {plug_top} ft to {plug_bottom} ft ({plug_length} ft total)")
        pdf.drawString(70, 490, f"Plug Volume / Sacks: {plug_vol_bbl:,.2f} bbl / {plug_sacks:,.0f} sacks")

        # Footer
        pdf.line(50, 50, 550, 50)
        pdf.drawString(50, 35, "Generated automatically by PyMudCement-Optima System Engine.")

        pdf.showPage()
        pdf.save()
        buffer.seek(0)
        return buffer

    pdf_file = compile_pdf_report()

    st.download_button(
        label="📥 Download Engineering PDF Summary Report",
        data=pdf_file,
        file_name=f"PyMudCement_Report_{st.session_state.worker_id}.pdf",
        mime="application/pdf"
    )

!pip install streamlit pyngrok numpy matplotlib plotly reportlab -q

# Step 1: Install all required Python packages
!pip install streamlit pyngrok numpy matplotlib plotly reportlab pandas -q

import os
from pyngrok import ngrok

# Step 2: Set your ngrok auth token
ngrok.set_auth_token("3EtaANi5u9FWbJ8AD3KHhBMe5v2_6cgRJpikisPEZMQZ2bm6L")

# Step 3: Stop any previous running instances to prevent port conflicts
os.system("pkill streamlit")
ngrok.kill()

# Step 4: Start Streamlit in the background
os.system("streamlit run app.py &")

# Step 5: Generate the public URL
public_url = ngrok.connect(8501)
print(f"🚀 Your Interactive Colab App is Live at: {public_url}")